### ISSUE TITLE
Support for Storybook 6

### ISSUE THREAD

**Issue by ganyuehn** [mertkahyaoglu/storybook-zeplin#11]
Hi, first thanks for the great plugin, it's really helpful. Can I ask if you would update dependency for this to support Storybook 6? 
I'm currently having a dependency issue:

```npm ERR! Could not resolve dependency:
npm ERR! peer @storybook/addons@"^5.0.0" from storybook-zeplin@1.1.3
npm ERR! node_modules/storybook-zeplin
npm ERR!   dev storybook-zeplin@"*" from the root project
npm ERR!
```

**Comment by dbvisel** [comment]
Same problem!

**Comment by mertkahyaoglu** [comment]
Hey @ganyuehn and @dbvisel. Thanks for letting me know. I released a fix version. Could you try after upgrading?

**Comment by dbvisel** [comment]
Works perfectly. Thanks so much!
