### ISSUE TITLE
Tab-content does not reload when switching components

### ISSUE THREAD

**Issue by kaiiiib** [mertkahyaoglu/storybook-zeplin#17]
When switching components in Storybook, the Zeplin tab does still show the Zeplin image of the previously selected component instead of reloading and showing the image of the currently selected component.

This behaviour starts to happen only when a Zeplin links/image has been selected via the dropdown and will remain until a manual page reload.

**Comment by mertkahyaoglu** [comment]
@kaiiiib Thanks for reporting this. It should be fixed with v1.3.0.
