### ISSUE TITLE
Add pixel diff functionality

### ISSUE THREAD

**Issue by mertkahyaoglu** [mertkahyaoglu/storybook-zeplin#2]
This feature shows difference between Zeplin designs and rendered components in pixels.

**Comment by yannbf** [comment]
This sounds incredible! Let me know if I can help somehow!
Would be also awesome if it was possible somehow to overlay the design on top of the component, with some transparency and zoom levels. Kind of like this feature from zeplin:
https://support.zeplin.io/en/articles/1437093-comparing-app-website-with-designs-using-pop-out

**Comment by mertkahyaoglu** [comment]
Thanks @yannbf ❤️ 

> Would be also awesome if it was possible somehow to overlay the design on top of the component

I don't think it would be possible due to the limitation of Storybook API. I was thinking something like plotting differences in addon panel using a tool like [pixelmatch](https://github.com/mapbox/pixelmatch). It can be toggled with a button.

**Comment by yannbf** [comment]
Yeah, makes sense.. I guess they're using electron or similar, so that provides APIs for such functionality.
I really like the idea for the visual diffing, it's kind of what chromatic does. So you'd make a screenshot of the iframe and compare with the design, right?

**Comment by mertkahyaoglu** [comment]
Yeah, that's right. I'm looking for ways to get the iframe's dom element right now so we can get a screenshot of it.

**Comment by yannbf** [comment]
> Yeah, that's right. I'm looking for ways to get the iframe's dom element right now so we can get a screenshot of it.

`document.querySelector('#storybook-preview-iframe').contentDocument` should do it!

**Comment by mertkahyaoglu** [comment]
> document.querySelector('#storybook-preview-iframe').contentDocument should do it!

Hmm, that's one way to do it, I guess. I was looking for a solution provided by the API but this can work for now. Thanks 👍

**Comment by mertkahyaoglu** [comment]
Resolved via #13
