### ISSUE TITLE
Show multiple Zeplin previews per component

### ISSUE THREAD

**Issue by kaiiiib** [mertkahyaoglu/storybook-zeplin#20]
Since Storybook can include multiple elements within one component, it would be useful to allow multiple Zeplin previews (incl. their respective links) per component as well. This would allow users to stick with their preferred presentation structure of components while also having all relevant Zeplin previews in one view.

Manipulated screenshot to demonstrate the idea:

![image](https://user-images.githubusercontent.com/42468249/112827560-caf8f080-908e-11eb-826e-14f775de1240.png)

Storybook code could then maybe be something like this:
```
parameters: {
    zeplinLink: [
        {
            name: "Default",
            link: [
                    "https://app.zeplin.io/...coid=123",
                    "https://app.zeplin.io/...coid=456",
                    "https://app.zeplin.io/...coid=789"
            ]
        },
        {
            name: "Another Option so select",
            link: [
                    "https://app.zeplin.io/...coid=987",
                    "https://app.zeplin.io/...coid=654",
                    "https://app.zeplin.io/...coid=321"
            ]
        },
    ],
}
```

**Comment by yannbf** [comment]
That sounds like an interesting idea, but it could easily get messy once the designs are larger I think. It would also clash with the pop-out feature.
What designers could also do is make a single design that bundles the variants, and on Storybook you'd use a single link instead.

What do you think @mertkahyaoglu ?

**Comment by mertkahyaoglu** [comment]
I agree with this;
> but it could easily get messy once the designs are larger I think.

@kaiiiib Also, not sure how viable this case is. What would the designs for "Another Option so select" be look like? I mean in the story, we can see three states of input and we can add multiple links for that one story. So via select input, we can navigate through those states. But in your case, you collected all those states in one option. I can't imagine what other options we need here. Could you give an example for those? I'm trying to understand the use case here.

**Comment by kaiiiib** [comment]
The reason to show all the variants of a component in one story is to align the story and the Zeplin preview while not having to touch the Sketch library file too much. It is also to **get a better overview and not having to switch/select too much within the dropdown list while comparing and verifying the implementation vs the design**. Whether those "grouped views" (or whatever they could be called) of Zeplin components are used to show only different states, groups of elements of the same family, or even composed components could then be up to the designers and developers.

Hope that make it a bit more clear. Or maybe there is another idea to achieve that?

> What designers could also do is make a single design that bundles the variants, and on Storybook you'd use a single link instead.

True, that's a valid suggestion. Although that would mean to create (Sketch Library) Symbols/Components just for the Storybook presentation. Could be confusing and redundant for designers at least. Hence the idea to solve that in Storybook somehow.

> What would the designs for "Another Option so select" be look like?

The _"Another option to select"_ is just a second dropdown-list option, so when opening the dropdown of the example code there would be two elements so select: "Default" und "Another option to select". Choosing the second dropdown list element would then show components 987, 654 and 321. It doesn't make much sense in this example screenshot, just thought this way it is more consistent and easier to use, also code-wise.

However, I understand that this might conflict with other features or future features such as the description text etc. - I won't be mad if you reject this feature idea ;)

> It would also clash with the pop-out feature.

What do you mean by "pop-out feature"? Is that the _"Show overlay"_ function in [your Storybook example page](https://storybook-zeplin.netlify.app/?path=/story/example-button--button-normal)?
Looks really interesting - but how do I use that correctly? Seems to be a bit difficult to match the position of the story element and the overlay. (Hmmm...individual drag&drop positioning of the overlay could be a future improvement.)
