### ISSUE TITLE
storybook 6.2.1 

### ISSUE THREAD

**Issue by jonwilliams-bluescape** [mertkahyaoglu/storybook-zeplin#21]
using yarn 2 as my package manager, compiles fine, then:

Cannot find module 'storybook-zeplin/register'

Tried blowing away the yarn cache and reinstalling.

Haven't tried npm yet

**Comment by jonwilliams-bluescape** [comment]
nevermind -- i was yarn.lock'd to a 6.2 release candidate. Seems to at least load the addon properly now.

**Comment by mertkahyaoglu** [comment]
Glad you figured that out 👍🏼 Closing this then.
