### ISSUE TITLE
Icon image doesn't appear in Storybook addon catalog

### ISSUE THREAD

**Issue by domyen** [mertkahyaoglu/storybook-zeplin#22]
![image](https://user-images.githubusercontent.com/263385/114194993-095b9e80-991e-11eb-8f06-1f299972ddcf.png)

This is probably because the Twitter avatar URL is no longer correct in [package.json](https://github.com/mertkahyaoglu/storybook-zeplin/blob/master/package.json#L57). You might want to reference a different static asset by uploading it to GitHub or your website.

**Comment by mertkahyaoglu** [comment]
@domyen I fixed the url in package.json but the logo is still not showing up in storybook addon page. Is that a cache issue?
