### ISSUE TITLE
Image not showing - 403 error from Zeplin

### ISSUE THREAD

**Issue by gidich** [mertkahyaoglu/storybook-zeplin#29]
I'm not sure if I've done something wrong but images are no longer showing - getting 403 error.

I've put in a new Zeplin API key in place and did not help.

**Comment by gidich** [comment]
This is what I'm seeing:

![image](https://user-images.githubusercontent.com/1847881/129924801-80c1cef2-f2fa-4b1a-a068-7cc9f60e5dce.png)

**Comment by iasim** [comment]
I am experiencing the same issue

**Comment by nguyenduy** [comment]
I am experiencing the same issue

**Comment by mertkahyaoglu** [comment]
Thanks for the issue @gidich. Which version of Storybook are you guys using? /cc @iasim @nguyenduy .
@yannbf Could this be related to #27?

**Comment by gidich** [comment]
My Storybook version is @storybook/react v6.3.7

**Comment by gidich** [comment]
I think that the issue must have been on Zeplin's side, the issue is no longer happening.

**Comment by gidich** [comment]
Thank you @mertkahyaoglu for this plugin and for your quick response!

**Comment by mertkahyaoglu** [comment]
Awesome. Glad to hear it's resolved. Let's see other folks are still having this @iasim @nguyenduy .

**Comment by adamgasiorek** [comment]
@mertkahyaoglu for me this problem still exist, i am trying to contact with zeplin but maybe you can provide some information ?
