### ISSUE TITLE
Development environment

### ISSUE THREAD

**Issue by ergunsh** [mertkahyaoglu/storybook-zeplin#3]
This is a great addon with lots of opportunities for development!

I just wanted to play around with it but couldn't find steps to build and run locally. I also don't have any project with storybook in it, so it was a little hard for me to get started.

It would be great if there was instructions to build and run the addon locally. Additionally, having a dummy storybook running in the project could speed up the things a little bit.

**Comment by mertkahyaoglu** [comment]
Thanks @ergunsh 🤟 

That's a really good idea. I created another project while developing the addon. It would have been much easier if I integrated Storybook here in this repo. I'll add one for development 👍
