### ISSUE TITLE
Build failing with 1.5.2-rc.0

### ISSUE THREAD

**Issue by yannbf** [mertkahyaoglu/storybook-zeplin#32]
After trying out `1.5.2-rc.0` of this addon and adding `react-element-to-jsx-string` as the README states, I got this problem in my terminal:

![image](https://user-images.githubusercontent.com/1671563/137274829-735411b8-102e-4205-88c5-52af2a56be5d.png)

Seems like `@zeplin/storybook-inspector` is not properly lazy loading framework-specific code, so in my React app it expects Vue to be installed.

## Considerations

A recent PR was merged [#31: Add sending storybook data to parent frame](https://github.com/mertkahyaoglu/storybook-zeplin/pull/31) which changed the README, however the latest release is a pre-release. This means that people will now follow the instructions in README but not install the correct version. Also, given that this is a breaking change, I would recommend bumping up a major version number and not a patch if possible

cc @mertkahyaoglu @skarahoda

**Comment by mertkahyaoglu** [comment]
This should be fixed now.
