### ISSUE TITLE
Same Origin Error in Chrome

### ISSUE THREAD

**Issue by jonwilliams-bluescape** [mertkahyaoglu/storybook-zeplin#40]
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://app.zeplin.io') does not match the recipient window's origin ('http://localhost:6006').

Our project config is pretty gnarly, so I figured I was doing something wrong.
Then I opened storybook in Firefox and everything worked fine.

The Firefox console shows the same message, but *does* show the corresponding Zeplin addon etc. Chrome behaves as though there's no Zeplin addon registered. So, I'm not 100% sure that Chrome's failure is due to the postMessage, but that's all I have to go on at the moment.

**Comment by jonwilliams-bluescape** [comment]
Hmm... cleared all cookies, local storage, etc and everything is fine so closing.

**Comment by mertkahyaoglu** [comment]
@jonwilliams-bluescape Glad you figured it out 😄

**Comment by umutHatipoglu** [comment]
> Hmm... cleared all cookies, local storage, etc and everything is fine so closing.

Im having exactly same problem, clearing cookies and local storages not solve my problem. Any suggestion here @mertkahyaoglu

**Comment by prarabdhb** [comment]
@mertkahyaoglu Facing the same issue. https://github.com/mertkahyaoglu/storybook-zeplin/issues/54

Is there a fix for the same?

**Comment by yuqu** [comment]
Replied about the issue here: https://github.com/mertkahyaoglu/storybook-zeplin/issues/54#issuecomment-1228462813
