### ISSUE TITLE
[feature-request] Tabbed view for multiple layouts per story

### ISSUE THREAD

**Issue by yannbf** [mertkahyaoglu/storybook-zeplin#5]
First of all, just wanted to say that this addon is great and super useful, thanks for doing this!!
In my use case, I have different layouts in zeplin for desktop, mobile and tablet. With this addon it's not currently possible to attach multiple resources per story, so my solution is to do like:
```jsx
export const Desktop = () => {
  return <MyComponent />;
};

Default.story = {
  parameters: {
    zeplinLink:
      'https://link.to.desktop/design'
  }
};

export const Mobile = () => {
  return <MyComponent/>;
};

Mobile.story = {
  parameters: {
    zeplinLink:
      'https://link.to.mobile/design',
    viewport: {
      defaultViewport: 'iphonex'
    }
  }
};
```

Which is fine, although it requires me to create a combination of stories which is not really scalable. 

It's just an idea, but **It would be incredible if I could do like:**

```js
export const Default = () => {
  return <MyComponent />;
};

Default.story = {
  parameters: {
    zeplinLink:
      'https://link.to.desktop/design' // <-- if it's string, just loads that asset
  }
};

export const WithMultipleAssets = () => {
  return <MyComponent />;
};

WithMultipleAssets.story = {
  parameters: {
    zeplinLink: { // <-- if it's object, presents a select or tab that switches between assets
        desktop: 'https://link.to.desktop/design',
        mobile: 'https://link.to.mobile/design',
        newDesign: 'https://link.to.desktop/design'
    }
  }
};
```

This way it's not only easy to check different viewport designs, but also to maybe compare like old/new design, etc.

I'm definitely willing to add or help add this functionality to this addon. What do you think? :D

**Comment by mertkahyaoglu** [comment]
Thanks for the issue @yannbf.

I thought about attaching multiple layouts to a story while creating this addon but then I assumed that those layouts would be separate stories so I didn't do it. Looking at your case, seeing every layouts of a responsive component makes sense to me now. It would be great if you could help on this feature 👍
