### ISSUE TITLE
Zeplin preview of multiple links gets stuck

### ISSUE THREAD

**Issue by Gerson4G** [mertkahyaoglu/storybook-zeplin#51]
Hi All. And thank you for this addon!

**Issue found:**
Turns out I added in a story multiple Zeplin links, just as the documentation specify.
Then I added a single Zeplin link in another story.
Turns out that when checking the different Zeplin screens on the first story, when going to the other component's story it gets stuck with Zeplin page of component 1, only way to fix this is by refreshing the browser.

Tried Firefox and Chrome with no luck.

**Screen recording of the actual issue:**
https://user-images.githubusercontent.com/12521959/156455161-3574c3ea-b14a-4f49-af83-0bebbd220d57.mov

**Below some of the versions installed ad the moment of the issue**
@storybook/react: "6.4.19",
@zeplin/sdk: "1.11.0",
storybook-zeplin: "1.7.1",
@storybook/core: "6.4.19",
@storybook/core: "17.0.2"

Let me know if I can help anymore and gladly will send the info over.

**Comment by mertkahyaoglu** [comment]
@Gerson4G Thanks for the issue. I'm looking into this.

**Comment by Gerson4G** [comment]
Thank you so much for so a fast response! Very appreciated.
