### ISSUE TITLE
Console error on load/refresh

### ISSUE THREAD

**Issue by kinoli** [mertkahyaoglu/storybook-zeplin#54]
Seeing this console error when loading storybook.

**Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://app.zeplin.io') does not match the recipient window's origin ('http://localhost:6006').**

**Comment by prarabdhb** [comment]
We are facing the same issue when we do the integration. Is there anyway to solve this?

**Comment by yuqu** [comment]
Sorry for the confusion, you can just ignore this error. It is a call to signal Zeplin app when you try to initialize [Storybook integration](https://support.zeplin.io/en/articles/5674596-connecting-your-storybook-instance-with-zeplin). 

We'll look for an alternative way for signalling to remove the error.
