### ISSUE TITLE
Cannot use Zeplin links with seid parameter

### ISSUE THREAD

**Issue by mannyblum** [mertkahyaoglu/storybook-zeplin#58]
Good day!

I was trying out this plugin today and ran into an issue. All the examples use a `coid` param in zeplin URLs but Zeplin now seems to use an `seid` param instead.

```
parameters: {
    zeplinLink: 'https://app.zeplin.io/project/PROJECT_ID/styleguide/components?seid=COMPONENT_ID'
},
```

The Zeplin tab in storybook shows me the following message:

```
Zeplin link is invalid.

You are currently logged in as USERNAME. If you prefer using another account, you can log out first.
```

has anyone else run into this?

**Comment by yuqu** [comment]
`seid` refers to a component section. Make sure to get a component link by selecting the component.
